README.md
Fix logo path on the documentation
It was broken
=> docs: fix logo path

README.md
=> docs: added link to diconium website adobe io on the image

.github/PULL_REQUEST_TEMPLATE.md
=> docs: small update to PR template

cif/carts/src/mappers/CartEntryMapper.ts, cif/carts/src/mappers/CartMapper.ts, cif/carts/src/mappers/ShippingInfoMapper.ts, cif/carts/test/resources/adobeCartEntry.json, cif/products/src/helpers/ProductsHelper.ts, cif/products/src/mappers/ProductMapper.ts, cif/products/src/mappers/ProductVariantMapper.ts, cif/products/test/resources/adobe-product-de.json, cif/products/test/resources/adobe-product-external-asset.json, cif/products/test/resources/adobe-product.json, cif/products/test/resources/hybris-product-de.json, cif/products/test/resources/hybris-product.json, cif/products/test/resources/search/adobe-search-product.json, cif/products/test/resources/search/hybris-search-product-page0.json, cif/products/test/unit/getProductById.spec.ts, cif/products/test/unit/getSearchProducts.spec.ts
Also updated corresponding tests
Update product and product variant mappings and their corresponding tests.
Mappings were not up to date
=> refactor: Update product and product variant mappings

cif/carts/README.md, cif/carts/package.json, cif/categories/README.md, cif/categories/package.json, cif/products/README.md, cif/products/package.json
docs: Create README.md files for the public packages
Also added repository parameters to package.json
Documentation update
=> docs: Create README.md files for the public packages

cif/carts/package.json, cif/categories/package.json, cif/common/package.json, cif/products/package.json, cif/products/src/mappers/ProductVariantMapper.ts, cif/products/test/resources/search/hybris-search-product-page0.json
=> fix: ProductVariantMapper when stock object is not present

cif/carts/CHANGELOG.md, cif/carts/package.json, cif/categories/CHANGELOG.md, cif/categories/package.json, cif/common/CHANGELOG.md, cif/common/package.json, cif/products/CHANGELOG.md, cif/products/package.json
- @diconium/commerce-cif-hybris-carts@1.2.0
- @diconium/commerce-cif-hybris-categories@1.2.0
- @diconium/commerce-cif-hybris-common@1.2.0
- @diconium/commerce-cif-hybris-products@1.2.0
=> docs(all): Bump versions

.circleci/config.yml, cif/carts/CHANGELOG.md, cif/carts/package.json, cif/categories/CHANGELOG.md, cif/categories/package.json, cif/common/CHANGELOG.md, cif/common/package.json, cif/products/CHANGELOG.md, cif/products/package.json, package.json
Added configurations for build, deploy and publish process
Added configurations for build, deploy and publish process.
It now has different behaviours for features branches and master branch
Automate the deploy/publish process
=> build: circle ci config

customer-deployment/README.md
Updated documentation
Updated readme files
Readme files were not fully up to date
=> docs: Updated readme

.circleci/config.yml
We need a way to make an automatic deploy and publish as soon as we do a new commit on master branch.
=> feat: add support for automatic deploy and publish from circle ci

.circleci/config.yml
=> feat: added fingerprint for ssh deploy key with write access

.circleci/config.yml
=> fix(ci): add ssh StrictHostKeyChecking=no to set git settings

cif/carts/src/mappers/CartMapper.ts
Verify if billingAddress exists in paymentInfo before mapping it.
Avoids undefined destructuring when the paymentInfo does not contain an address.
Fixes a bug when there is no billingAddress on paymentInfo
=> Update CartMapper - bilingAddress verification

cif/categories/src/mappers/CategoryMapper.ts, cif/categories/src/mappers/PagedResponseCategoryMapper.ts, cif/categories/test/resources/get-flattened-categories-adobe-valid-response.json, cif/categories/test/unit/getCategories.spec.ts
… map the parent of the current category in a flat hierarchy.
Mapped the parent of each category according to the CIF specification so that the models appear in a tree manner on category and product picker
Mapped the parent of each category according to the CIF specification so that the models appear in a tree manner on category and product picker
This solves the problem of not able to see the tree view of the categories on the Adobe Product and Category picker
=> Added Parent to each category for a flat categories call

cif/carts/package.json, cif/categories/package.json, cif/products/package.json, cif/shoppinglists/package.json, yarn.lock
Updated the version for libraries namely : client, i18n,  core, validators
This new version introduces the xapi key as the base64 encoded string in the request header.
This change is required so that we can add an extra level of security and tracking via X-API-KEY in the header.
=> Fix : Updated Core Dependencies

cif/carts/src/clients/GetCartByIdClient.ts, cif/carts/src/mappers/CartMapper.ts
Passing cart object as-is to the cart mapper and deciding the cart id based on the input settings.
One of the clients of this library wanted to get the user object from within the cart object which was passed by Hybris. As the object passed from Hybris was being directly mutated and only one property was being mapped and all other ignored, the client was never able to get the email from the user object.
=> feat: passing cart object as-is to the cart mapper 

cif/carts/src/mappers/CartMapper.ts
=> fix: renamed variable to bump version

cif/carts/src/mappers/CartMapper.ts
=> add totalPriceWithTax currency validation

cif/carts/package.json, cif/carts/src/clients/DeleteCartClient.ts, cif/carts/src/clients/DeleteCartEntryClient.ts, cif/carts/src/clients/DeleteCouponClient.ts, cif/carts/src/clients/DeletePaymentClient.ts, cif/carts/src/clients/DeleteShippingAddressClient.ts, cif/carts/src/clients/DeleteShippingMethodClient.ts, cif/categories/package.json, cif/products/package.json, cif/shoppinglists/package.json, cif/shoppinglists/src/clients/DeleteShoppingListEntryByIdClient.ts, yarn.lock
Updates the base client dependencies
=> Update the base client dependencies

cif/carts/package.json, cif/categories/package.json, cif/products/package.json, cif/shoppinglists/package.json
bumping @diconium/commerce-cif-hybris-clients version to latest
Changes to @diconium/commerce-cif-hybris-clients dependency where the promise rejection was not returned and exceptions were not gracefully handled.
=> bumping http client version to latest

cif/carts/serverless.yml, cif/categories/serverless.yml, cif/common/serverless.yml, cif/products/serverless.yml, cif/shoppinglists/serverless.yml, customer-deployment/serverless.yml
set nodejs version to default, as requested by adobe
s.o.
Requested by Adobe
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code passes the code style as defined by TSLint.
- [ X] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] I have read the **CONTRIBUTING** document.
- [ X] I have added tests to cover my changes and the overall coverage did not decrease.
- [ X] I ran all tests locally and they pass.
- [ X] All unit tests …
=> feat: set nodejs version to default
